name: Deploy docker image frontend

on:
  push:
    branches:
      - main

jobs:
  push_to_registry:
    name: Push Docker image
    runs-on: ubuntu-latest
    steps:
      - 
        name: Check repository
        uses: actions/checkout@v3

      -
        name: Log to Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_KEY }}

      - 
        name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: bartoszmajkowski/better-schedule

      -
        name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: bartoszmajkowski/better-schedule:frontend

